### ISSUE TITLE
Is Python2 Or Python3?

### ISSUE THREAD

**Issue by 308172100** [jx9527/FHSS-Hopping-Estimation#1]
There is something wrong when I CMake the mod:

-- Found Git: /usr/bin/git  
-- No C++ sources... skipping lib/
-- No C++ sources... skipping swig/
-- Could NOT find PythonInterp (missing: PYTHON_EXECUTABLE) (Required is at least version "2")
CMake Error at cmake/Modules/GrPython.cmake:113 (file):
  file FILE([TO_CMAKE_PATH|TO_NATIVE_PATH] path result) must be called with
  exactly three arguments.
Call Stack (most recent call first):
  python/CMakeLists.txt:23 (include)

-- Could NOT find PythonInterp (missing: PYTHON_EXECUTABLE) (Required is at least version "2")
CMake Error at cmake/Modules/GrPython.cmake:113 (file):
  file FILE([TO_CMAKE_PATH|TO_NATIVE_PATH] path result) must be called with
  exactly three arguments.
Call Stack (most recent call first):
  apps/CMakeLists.txt:20 (include)

-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Configuring incomplete, errors occurred!
See also "/home/hackrf/gr-FHSS/build/CMakeFiles/CMakeOutput.log".

**Comment by jx9527** [comment]
python3
